pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  buildId: "1$(Build.BuildId)"

steps:
# Ensure Java version 11 installed
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
# Print buildId
- script: |
    echo "BuildId = $(buildId)"
# Install SonarScanner
- script: |
    dotnet tool install --global dotnet-sonarscanner
# Begin SonarScanner#
- script: |
    %USERPROFILE%\.dotnet\tools\dotnet-sonarscanner begin /k:"c1gdoyle_Dunk.Tools.Monitoring" /o:"c1gdoyle" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(SONAR_TOKEN)" /d:sonar.cs.vstest.reportsPaths="**\TestResults\*.trx" /d:sonar.cs.opencover.reportsPaths="**\coverage.netcoreapp3.1.opencover.xml"
# Build source, tests and run tests for netcoreapp3.1(with coverage)
- script: |
    dotnet build ./Dunk.Tools.Monitoring.sln --configuration $(buildConfiguration)
    dotnet test ./Dunk.Tools.Monitoring.Test/Dunk.Tools.Monitoring.Test.csproj --configuration $(buildConfiguration) --no-build --framework net472 
    dotnet test ./Dunk.Tools.Monitoring.Test/Dunk.Tools.Monitoring.Test.csproj --configuration $(buildConfiguration) --no-build --framework netcoreapp3.1 --logger:trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
# End SonarScanner
- script: |
    %USERPROFILE%\.dotnet\tools\dotnet-sonarscanner end /d:sonar.login="$(SONAR_TOKEN)"
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'